---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/content
  label: Content
  create: all
  match: "**/*"
- type: directory
  path: content/UHI
  label: Uhi
  create: all
  match: "**/*"
- type: directory
  path: content/7-exiting-sandbox
  label: 7 exiting sandbox
  create: all
  match: "**/*"
- type: directory
  path: content/6-M1-APIs
  label: 6 m1 apis
  create: all
  match: "**/*"
- type: directory
  path: content/4-building-a-phr-app
  label: 4 building a phr app
  create: all
  match: "**/*"
- type: directory
  path: content/3-get-health-records
  label: 3 get health records
  create: all
  match: "**/*"
- type: directory
  path: content/2-sharing-health-records
  label: 2 sharing health records
  create: all
  match: "**/*"
- type: directory
  path: content/1-basics
  label: 1 basics
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
